#############################################################################
# Makefile for building: ArthursTable
# Generated by qmake (3.1) (Qt 5.12.7)
# Project:  ArthursTable.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile ArthursTable.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/qt5/QtCore -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSerialPort -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5 -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ArthursTable1.0.0
DISTDIR = /data/Projects/ArthursTable/.tmp/ArthursTable1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lopus -lpulse -lm /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5SerialPort.so /usr/lib64/libQt5Core.so /usr/lib64/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = algorithms.cpp \
		ambient.cpp \
		audioio.cpp \
		buffer.cpp \
		bulktransfer.cpp \
		control.cpp \
		convert.cpp \
		diceroller.cpp \
		effectconfig.cpp \
		facilitymanager.cpp \
		filewatcher.cpp \
		focus.cpp \
		headtracker.cpp \
		infopanel.cpp \
		main.cpp \
		mainwindow.cpp \
		marker.cpp \
		messages.cpp \
		npcviewer.cpp \
		painterface.c \
		playercomlink.cpp \
		roomacoustics.cpp \
		setup.cpp \
		sketchpad.cpp \
		soundfx.cpp \
		streammanager.cpp \
		tableselector.cpp \
		teamselector.cpp \
		tools.cpp \
		viewer.cpp \
		visualizer.cpp \
		voiceeffect.cpp \
		vumeter.cpp moc_ambient.cpp \
		moc_audioio.cpp \
		moc_bulktransfer.cpp \
		moc_control.cpp \
		moc_diceroller.cpp \
		moc_effectconfig.cpp \
		moc_facilitymanager.cpp \
		moc_filewatcher.cpp \
		moc_focus.cpp \
		moc_headtracker.cpp \
		moc_infopanel.cpp \
		moc_mainwindow.cpp \
		moc_marker.cpp \
		moc_messages.cpp \
		moc_npcviewer.cpp \
		moc_playercomlink.cpp \
		moc_roomacoustics.cpp \
		moc_setup.cpp \
		moc_sketchpad.cpp \
		moc_streammanager.cpp \
		moc_tableselector.cpp \
		moc_teamselector.cpp \
		moc_viewer.cpp \
		moc_visualizer.cpp \
		moc_voiceeffect.cpp \
		moc_vumeter.cpp
OBJECTS       = algorithms.o \
		ambient.o \
		audioio.o \
		buffer.o \
		bulktransfer.o \
		control.o \
		convert.o \
		diceroller.o \
		effectconfig.o \
		facilitymanager.o \
		filewatcher.o \
		focus.o \
		headtracker.o \
		infopanel.o \
		main.o \
		mainwindow.o \
		marker.o \
		messages.o \
		npcviewer.o \
		painterface.o \
		playercomlink.o \
		roomacoustics.o \
		setup.o \
		sketchpad.o \
		soundfx.o \
		streammanager.o \
		tableselector.o \
		teamselector.o \
		tools.o \
		viewer.o \
		visualizer.o \
		voiceeffect.o \
		vumeter.o \
		moc_ambient.o \
		moc_audioio.o \
		moc_bulktransfer.o \
		moc_control.o \
		moc_diceroller.o \
		moc_effectconfig.o \
		moc_facilitymanager.o \
		moc_filewatcher.o \
		moc_focus.o \
		moc_headtracker.o \
		moc_infopanel.o \
		moc_mainwindow.o \
		moc_marker.o \
		moc_messages.o \
		moc_npcviewer.o \
		moc_playercomlink.o \
		moc_roomacoustics.o \
		moc_setup.o \
		moc_sketchpad.o \
		moc_streammanager.o \
		moc_tableselector.o \
		moc_teamselector.o \
		moc_viewer.o \
		moc_visualizer.o \
		moc_voiceeffect.o \
		moc_vumeter.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		ArthursTable.pro algorithms.h \
		ambient.h \
		audioio.h \
		buffer.h \
		bulktransfer.h \
		config.h \
		control.h \
		convert.h \
		diceroller.h \
		effectconfig.h \
		facilitymanager.h \
		filewatcher.h \
		focus.h \
		headtracker.h \
		infopanel.h \
		mainwindow.h \
		marker.h \
		messages.h \
		npcviewer.h \
		painterface.h \
		playercomlink.h \
		roomacoustics.h \
		setup.h \
		sketchpad.h \
		soundfx.h \
		streammanager.h \
		tableselector.h \
		teamselector.h \
		tools.h \
		types.h \
		viewer.h \
		visualizer.h \
		voiceeffect.h \
		vumeter.h algorithms.cpp \
		ambient.cpp \
		audioio.cpp \
		buffer.cpp \
		bulktransfer.cpp \
		control.cpp \
		convert.cpp \
		diceroller.cpp \
		effectconfig.cpp \
		facilitymanager.cpp \
		filewatcher.cpp \
		focus.cpp \
		headtracker.cpp \
		infopanel.cpp \
		main.cpp \
		mainwindow.cpp \
		marker.cpp \
		messages.cpp \
		npcviewer.cpp \
		painterface.c \
		playercomlink.cpp \
		roomacoustics.cpp \
		setup.cpp \
		sketchpad.cpp \
		soundfx.cpp \
		streammanager.cpp \
		tableselector.cpp \
		teamselector.cpp \
		tools.cpp \
		viewer.cpp \
		visualizer.cpp \
		voiceeffect.cpp \
		vumeter.cpp
QMAKE_TARGET  = ArthursTable
DESTDIR       = 
TARGET        = ArthursTable


first: all
####### Build rules

ArthursTable:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ArthursTable.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		ArthursTable.pro
	$(QMAKE) -o Makefile ArthursTable.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
ArthursTable.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ArthursTable.pro

qmake_all: FORCE


all: Makefile ArthursTable

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents algorithms.h ambient.h audioio.h buffer.h bulktransfer.h config.h control.h convert.h diceroller.h effectconfig.h facilitymanager.h filewatcher.h focus.h headtracker.h infopanel.h mainwindow.h marker.h messages.h npcviewer.h painterface.h playercomlink.h roomacoustics.h setup.h sketchpad.h soundfx.h streammanager.h tableselector.h teamselector.h tools.h types.h viewer.h visualizer.h voiceeffect.h vumeter.h $(DISTDIR)/
	$(COPY_FILE) --parents algorithms.cpp ambient.cpp audioio.cpp buffer.cpp bulktransfer.cpp control.cpp convert.cpp diceroller.cpp effectconfig.cpp facilitymanager.cpp filewatcher.cpp focus.cpp headtracker.cpp infopanel.cpp main.cpp mainwindow.cpp marker.cpp messages.cpp npcviewer.cpp painterface.c playercomlink.cpp roomacoustics.cpp setup.cpp sketchpad.cpp soundfx.cpp streammanager.cpp tableselector.cpp teamselector.cpp tools.cpp viewer.cpp visualizer.cpp voiceeffect.cpp vumeter.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_ambient.cpp moc_audioio.cpp moc_bulktransfer.cpp moc_control.cpp moc_diceroller.cpp moc_effectconfig.cpp moc_facilitymanager.cpp moc_filewatcher.cpp moc_focus.cpp moc_headtracker.cpp moc_infopanel.cpp moc_mainwindow.cpp moc_marker.cpp moc_messages.cpp moc_npcviewer.cpp moc_playercomlink.cpp moc_roomacoustics.cpp moc_setup.cpp moc_sketchpad.cpp moc_streammanager.cpp moc_tableselector.cpp moc_teamselector.cpp moc_viewer.cpp moc_visualizer.cpp moc_voiceeffect.cpp moc_vumeter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ambient.cpp moc_audioio.cpp moc_bulktransfer.cpp moc_control.cpp moc_diceroller.cpp moc_effectconfig.cpp moc_facilitymanager.cpp moc_filewatcher.cpp moc_focus.cpp moc_headtracker.cpp moc_infopanel.cpp moc_mainwindow.cpp moc_marker.cpp moc_messages.cpp moc_npcviewer.cpp moc_playercomlink.cpp moc_roomacoustics.cpp moc_setup.cpp moc_sketchpad.cpp moc_streammanager.cpp moc_tableselector.cpp moc_teamselector.cpp moc_viewer.cpp moc_visualizer.cpp moc_voiceeffect.cpp moc_vumeter.cpp
moc_ambient.cpp: ambient.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include ambient.h -o moc_ambient.cpp

moc_audioio.cpp: audioio.h \
		vumeter.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include audioio.h -o moc_audioio.cpp

moc_bulktransfer.cpp: bulktransfer.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include bulktransfer.h -o moc_bulktransfer.cpp

moc_control.cpp: control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		control.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include control.h -o moc_control.cpp

moc_diceroller.cpp: diceroller.h \
		vumeter.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include diceroller.h -o moc_diceroller.cpp

moc_effectconfig.cpp: effectconfig.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include effectconfig.h -o moc_effectconfig.cpp

moc_facilitymanager.cpp: facilitymanager.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include facilitymanager.h -o moc_facilitymanager.cpp

moc_filewatcher.cpp: filewatcher.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include filewatcher.h -o moc_filewatcher.cpp

moc_focus.cpp: focus.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include focus.h -o moc_focus.cpp

moc_headtracker.cpp: headtracker.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include headtracker.h -o moc_headtracker.cpp

moc_infopanel.cpp: infopanel.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		mapviewer.h \
		focus.h \
		facilitymanager.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h \
		npcviewer.h \
		dungeonviewer.h \
		viewer.h \
		algorithms.h \
		marker.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include infopanel.h -o moc_infopanel.cpp

moc_mainwindow.cpp: mainwindow.h \
		ambient.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		audioio.h \
		vumeter.h \
		diceroller.h \
		effectconfig.h \
		filewatcher.h \
		headtracker.h \
		infopanel.h \
		mapviewer.h \
		focus.h \
		facilitymanager.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		soundfx.h \
		npcviewer.h \
		dungeonviewer.h \
		viewer.h \
		algorithms.h \
		marker.h \
		messages.h \
		playercomlink.h \
		roomacoustics.h \
		setup.h \
		sketchpad.h \
		teamselector.h \
		voiceeffect.h \
		visualizer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_marker.cpp: marker.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include marker.h -o moc_marker.cpp

moc_messages.cpp: messages.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include messages.h -o moc_messages.cpp

moc_npcviewer.cpp: npcviewer.h \
		focus.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		facilitymanager.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include npcviewer.h -o moc_npcviewer.cpp

moc_playercomlink.cpp: playercomlink.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include playercomlink.h -o moc_playercomlink.cpp

moc_roomacoustics.cpp: roomacoustics.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include roomacoustics.h -o moc_roomacoustics.cpp

moc_setup.cpp: setup.h \
		headtracker.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include setup.h -o moc_setup.cpp

moc_sketchpad.cpp: sketchpad.h \
		bulktransfer.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include sketchpad.h -o moc_sketchpad.cpp

moc_streammanager.cpp: streammanager.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include streammanager.h -o moc_streammanager.cpp

moc_tableselector.cpp: tableselector.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include tableselector.h -o moc_tableselector.cpp

moc_teamselector.cpp: teamselector.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include teamselector.h -o moc_teamselector.cpp

moc_viewer.cpp: viewer.h \
		algorithms.h \
		tools.h \
		bulktransfer.h \
		config.h \
		control.h \
		types.h \
		convert.h \
		marker.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include viewer.h -o moc_viewer.cpp

moc_visualizer.cpp: visualizer.h \
		bulktransfer.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include visualizer.h -o moc_visualizer.cpp

moc_voiceeffect.cpp: voiceeffect.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		soundfx.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include voiceeffect.h -o moc_voiceeffect.cpp

moc_vumeter.cpp: vumeter.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /data/Projects/ArthursTable/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/data/Projects/ArthursTable -I/data/Projects/ArthursTable -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSerialPort -I/usr/include/qt5/QtWidgets -I/usr/include/qt5 -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include vumeter.h -o moc_vumeter.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

algorithms.o: algorithms.cpp algorithms.h \
		tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o algorithms.o algorithms.cpp

ambient.o: ambient.cpp ambient.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ambient.o ambient.cpp

audioio.o: audioio.cpp audioio.h \
		vumeter.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audioio.o audioio.cpp

buffer.o: buffer.cpp buffer.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buffer.o buffer.cpp

bulktransfer.o: bulktransfer.cpp bulktransfer.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bulktransfer.o bulktransfer.cpp

control.o: control.cpp control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control.o control.cpp

convert.o: convert.cpp convert.h \
		types.h \
		config.h \
		tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o convert.o convert.cpp

diceroller.o: diceroller.cpp diceroller.h \
		vumeter.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diceroller.o diceroller.cpp

effectconfig.o: effectconfig.cpp effectconfig.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effectconfig.o effectconfig.cpp

facilitymanager.o: facilitymanager.cpp facilitymanager.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facilitymanager.o facilitymanager.cpp

filewatcher.o: filewatcher.cpp filewatcher.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filewatcher.o filewatcher.cpp

focus.o: focus.cpp focus.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o focus.o focus.cpp

headtracker.o: headtracker.cpp headtracker.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o headtracker.o headtracker.cpp

infopanel.o: infopanel.cpp infopanel.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		mapviewer.h \
		focus.h \
		facilitymanager.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h \
		npcviewer.h \
		dungeonviewer.h \
		viewer.h \
		algorithms.h \
		marker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infopanel.o infopanel.cpp

main.o: main.cpp headtracker.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		mainwindow.h \
		ambient.h \
		audioio.h \
		vumeter.h \
		diceroller.h \
		effectconfig.h \
		filewatcher.h \
		infopanel.h \
		mapviewer.h \
		focus.h \
		facilitymanager.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		soundfx.h \
		npcviewer.h \
		dungeonviewer.h \
		viewer.h \
		algorithms.h \
		marker.h \
		messages.h \
		playercomlink.h \
		roomacoustics.h \
		setup.h \
		sketchpad.h \
		teamselector.h \
		voiceeffect.h \
		visualizer.h \
		tableselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ambient.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		audioio.h \
		vumeter.h \
		diceroller.h \
		effectconfig.h \
		filewatcher.h \
		headtracker.h \
		infopanel.h \
		mapviewer.h \
		focus.h \
		facilitymanager.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		soundfx.h \
		npcviewer.h \
		dungeonviewer.h \
		viewer.h \
		algorithms.h \
		marker.h \
		messages.h \
		playercomlink.h \
		roomacoustics.h \
		setup.h \
		sketchpad.h \
		teamselector.h \
		voiceeffect.h \
		visualizer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

marker.o: marker.cpp marker.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o marker.o marker.cpp

messages.o: messages.cpp messages.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messages.o messages.cpp

npcviewer.o: npcviewer.cpp npcviewer.h \
		focus.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		facilitymanager.h \
		streammanager.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o npcviewer.o npcviewer.cpp

painterface.o: painterface.c painterface.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o painterface.o painterface.c

playercomlink.o: playercomlink.cpp playercomlink.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playercomlink.o playercomlink.cpp

roomacoustics.o: roomacoustics.cpp roomacoustics.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o roomacoustics.o roomacoustics.cpp

setup.o: setup.cpp setup.h \
		headtracker.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setup.o setup.cpp

sketchpad.o: sketchpad.cpp sketchpad.h \
		bulktransfer.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sketchpad.o sketchpad.cpp

soundfx.o: soundfx.cpp soundfx.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundfx.o soundfx.cpp

streammanager.o: streammanager.cpp streammanager.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		painterface.h \
		buffer.h \
		headtracker.h \
		soundfx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o streammanager.o streammanager.cpp

tableselector.o: tableselector.cpp tableselector.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tableselector.o tableselector.cpp

teamselector.o: teamselector.cpp teamselector.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teamselector.o teamselector.cpp

tools.o: tools.cpp tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o tools.cpp

viewer.o: viewer.cpp viewer.h \
		algorithms.h \
		tools.h \
		bulktransfer.h \
		config.h \
		control.h \
		types.h \
		convert.h \
		marker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer.o viewer.cpp

visualizer.o: visualizer.cpp visualizer.h \
		bulktransfer.h \
		config.h \
		control.h \
		types.h \
		tools.h \
		convert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visualizer.o visualizer.cpp

voiceeffect.o: voiceeffect.cpp voiceeffect.h \
		control.h \
		config.h \
		types.h \
		tools.h \
		convert.h \
		bulktransfer.h \
		soundfx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voiceeffect.o voiceeffect.cpp

vumeter.o: vumeter.cpp vumeter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vumeter.o vumeter.cpp

moc_ambient.o: moc_ambient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ambient.o moc_ambient.cpp

moc_audioio.o: moc_audioio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audioio.o moc_audioio.cpp

moc_bulktransfer.o: moc_bulktransfer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bulktransfer.o moc_bulktransfer.cpp

moc_control.o: moc_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_control.o moc_control.cpp

moc_diceroller.o: moc_diceroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diceroller.o moc_diceroller.cpp

moc_effectconfig.o: moc_effectconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_effectconfig.o moc_effectconfig.cpp

moc_facilitymanager.o: moc_facilitymanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_facilitymanager.o moc_facilitymanager.cpp

moc_filewatcher.o: moc_filewatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filewatcher.o moc_filewatcher.cpp

moc_focus.o: moc_focus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_focus.o moc_focus.cpp

moc_headtracker.o: moc_headtracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_headtracker.o moc_headtracker.cpp

moc_infopanel.o: moc_infopanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infopanel.o moc_infopanel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_marker.o: moc_marker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_marker.o moc_marker.cpp

moc_messages.o: moc_messages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_messages.o moc_messages.cpp

moc_npcviewer.o: moc_npcviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_npcviewer.o moc_npcviewer.cpp

moc_playercomlink.o: moc_playercomlink.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playercomlink.o moc_playercomlink.cpp

moc_roomacoustics.o: moc_roomacoustics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_roomacoustics.o moc_roomacoustics.cpp

moc_setup.o: moc_setup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setup.o moc_setup.cpp

moc_sketchpad.o: moc_sketchpad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sketchpad.o moc_sketchpad.cpp

moc_streammanager.o: moc_streammanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_streammanager.o moc_streammanager.cpp

moc_tableselector.o: moc_tableselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tableselector.o moc_tableselector.cpp

moc_teamselector.o: moc_teamselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_teamselector.o moc_teamselector.cpp

moc_viewer.o: moc_viewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewer.o moc_viewer.cpp

moc_visualizer.o: moc_visualizer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_visualizer.o moc_visualizer.cpp

moc_voiceeffect.o: moc_voiceeffect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_voiceeffect.o moc_voiceeffect.cpp

moc_vumeter.o: moc_vumeter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vumeter.o moc_vumeter.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

